# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dedd0de39c770f5a65977c1273f72a61e9d0a691d36606f48c3b1847679451a81366d5438f0db2e9f55592f1ad5b330a02922b73d3b11d845ca0bd019cc42e20

test:
  secret_key_base: 62cb42c745398fcc10322c660d9c1bfc33b4aeb39af42ec5b59806e9406f1f13773e38f8799d01404cf7ea9f92c19eac1e604979e0eefc53aa85cae33556bf76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
